# Generated by Django 3.1.1 on 2020-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
