# Generated by Django 3.1.1 on 2020-09-15 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='favorite_user',
            field=models.ManyToManyField(related_name='favorite_board', through='community.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
