# Generated by Django 3.1.1 on 2020-10-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
