# Generated by Django 3.1.1 on 2020-10-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
