# Generated by Django 3.1.1 on 2020-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartens', '0002_auto_20200930_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='grade',
            field=models.SmallIntegerField(),
        ),
    ]
