# Generated by Django 3.1.1 on 2020-10-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartens', '0003_remove_review_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergartens.borough')),
            ],
        ),
        migrations.AddField(
            model_name='borough',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergartens.city'),
        ),
    ]
