# Generated by Django 3.1.1 on 2020-10-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartens', '0004_auto_20201006_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_director',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_environment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_teacher',
            field=models.FloatField(),
        ),
    ]
