# Generated by Django 3.1.1 on 2020-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartens', '0004_auto_20201006_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='image',
            field=models.ImageField(null=True, upload_to='kindergarten'),
        ),
    ]
