# Generated by Django 3.1.1 on 2020-10-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartens', '0006_auto_20201006_1806'),
        ('kindergartens', '0005_kindergarten_image'),
    ]

    operations = [
    ]
